export * from './nav.model';
export * from './card.model';
export * from './driver.model';
export * from './searchDriver.model';
export * from './searchPassengers.model';
export * from './tripsinfo.model';
export * from './driversCredit.model';
export * from './service-type.model';
export * from './manufactures.model';
